In [35]:
!pip install tensorflow

In [36]:
import tensorflow as tf

In [37]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator as IDG

In [38]:
from tensorflow import keras

In [39]:
from tensorflow.keras.models import Sequential

In [40]:
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D, Activation,BatchNormalization

In [41]:
from tensorflow.keras.preprocessing import image

In [32]:
#!wget https://www.dropbox.com/home/fer2013.csv

The name is too long, 635 chars total.
Trying to shorten...
New name is l.php?u=https:%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F31050%2F39603%2Fcompressed%2Ffer2013.csv.zip?GoogleAccessId=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com&Expires=1600294842&Signature=I9XRdIXgPEz3WxpzKTyZtmWN1IlD.
--2020-09-15 15:03:26--  https://l.facebook.com/l.php?u=https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F31050%252F39603%252Fcompressed%252Ffer2013.csv.zip%3FGoogleAccessId%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%26Expires%3D1600294842%26Signature%3DI9XRdIXgPEz3WxpzKTyZtmWN1IlDdLf4denFZXdgmVQuAeH94QPDBvoTuPX0EyVAStti8MShOeuskuYL6ZtLNoSjs8fHbTJcbpm%252F3rSpx6PmSIEcXTnODdYqXVbBJdH241Cj1NvPikP9bny0mf7PYSnf7wFjbTnCZbTRmCmOzfRA%252BrZD7ooEBj8miVUuk02%252Fe37aKByDsvrb8nLwZMoGUWcGQX4qjkr2cFftt4vC4d%252F95nPwTYZo2d1AVF2BZGl3Ha1QzZmng7gcGcdIJ1n1BF3nvr1Uyw2SQRgaLTX9uNSkuAstKUcxc3C9svjQA75s791%252BL5sTMM0ow5GGw1CZcg%253D%253D%26fbclid%3DIwAR10JaD8k5J6Pcpi84fpYShzC2

In [42]:
!unzip /content/fer2013.zip

Archive:  /content/fer2013.zip
  inflating: fer2013.csv             


In [43]:
import pandas as pd
import numpy as np

In [44]:
df= pd.read_csv(r"/content/fer2013.csv")

In [45]:
df.head()

emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training

In [46]:
df.shape

(35887, 3)

In [47]:
df = df.drop("Usage",axis=1)
df.head(2)

emotion                                             pixels
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  151 150 147 155 148 133 111 140 170 174 182 15...

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
train = df["pixels"]
test = df["emotion"]

In [50]:
x_train,x_test,y_train,y_test = train_test_split(train,test,test_size=0.1,random_state=10)

In [51]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(32298,) (3589,) (32298,) (3589,)


In [52]:
width,height =48,48

In [53]:
x_train1 =[]
for j in x_train:
    x_train1.append([int(p) for p in j.split()])  

In [54]:
x_train1 = np.array(x_train1)/255 #normalizing
x_train1.shape

(32298, 2304)

In [55]:
x_test1 =[]
for i in x_test:
    x_test1.append([int(p) for p in i.split()])

In [56]:
x_test1 = np.array(x_test1)/255 #normalizing
x_test1.shape

(3589, 2304)

In [57]:
x_train1 = x_train1.reshape(x_train1.shape[0],48,48,1) #reshaping the data
x_test1 = x_test1.reshape(x_test1.shape[0],48,48,1)

In [58]:
print(x_train1.shape)
print(x_test1.shape)

(32298, 48, 48, 1)
(3589, 48, 48, 1)


In [59]:
print(x_train1.dtype)
print(x_test1.dtype)

float64
float64


In [60]:
#convertinf to float32
x_train1_32 = x_train1.astype('float32')
x_test1_32 = x_test1.astype('float32')

In [61]:
model = Sequential()

In [62]:
#layer1
model.add(Conv2D(filters = 64,kernel_size=(5,5),input_shape=(48,48,1),padding='same'))
model.add(Conv2D(filters = 64,kernel_size=(5,5),padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Activation('relu'))

In [63]:
#layer2
model.add(Conv2D(filters = 128,kernel_size=(5,5),padding='same'))
model.add(Conv2D(filters = 128,kernel_size=(5,5),padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Activation('relu'))

In [64]:
#layer3
model.add(Conv2D(filters = 256,kernel_size=(3,3),padding='same'))
model.add(Conv2D(filters = 256,kernel_size=(3,3),padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Activation('relu'))

In [65]:
#layer4
model.add(Flatten())
model.add(Dense(128))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(rate=0.25))
model.add(Dense(7,activation='softmax'))

In [66]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=["accuracy"])

In [67]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 48, 48, 64)        1664      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 48, 48, 64)        102464    
_________________________________________________________________
batch_normalization (BatchNo (None, 48, 48, 64)        256       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 24, 24, 64)        0         
_________________________________________________________________
activation (Activation)      (None, 24, 24, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 128)       204928    
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 24, 24, 128)       4

In [68]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [69]:
#fitting the model
Epoch = 20
Batch_size =64
Lr =1e-3

In [70]:
model.fit(x_train1_32,y_train,epochs=Epoch,batch_size=Batch_size,validation_data=(x_test1_32,y_test))

Epoch 1/20
505/505 [==============================] - 26s 52ms/step - loss: 1.5966 - accuracy: 0.3877 - val_loss: 1.5499 - val_accuracy: 0.3929
Epoch 2/20
505/505 [==============================] - 26s 51ms/step - loss: 1.2591 - accuracy: 0.5233 - val_loss: 1.3518 - val_accuracy: 0.4720
Epoch 3/20
505/505 [==============================] - 26s 51ms/step - loss: 1.1380 - accuracy: 0.5705 - val_loss: 1.2021 - val_accuracy: 0.5442
Epoch 4/20
505/505 [==============================] - 25s 50ms/step - loss: 1.0621 - accuracy: 0.6032 - val_loss: 1.1887 - val_accuracy: 0.5391
Epoch 5/20
505/505 [==============================] - 26s 51ms/step - loss: 0.9969 - accuracy: 0.6283 - val_loss: 1.2200 - val_accuracy: 0.5347
Epoch 6/20
505/505 [==============================] - 26s 51ms/step - loss: 0.9304 - accuracy: 0.6563 - val_loss: 1.2175 - val_accuracy: 0.5564
Epoch 7/20
505/505 [==============================] - 26s 51ms/step - loss: 0.8581 - accuracy: 0.6806 - val_loss: 1.2134 - val_accuracy:

In [71]:
y_pred = model.predict_classes(x_test1_32)
y_pred

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([5, 2, 5, ..., 4, 4, 0])

In [72]:
print(y_pred[:10])

[5 2 5 2 2 6 2 6 1 5]


In [73]:
print(np.argmax(y_test[:10],axis=1))

[5 2 5 6 2 6 2 0 1 2]


In [74]:
from sklearn.metrics import confusion_matrix

In [77]:
confusion_mat = confusion_matrix(np.argmax(y_test,axis=1),y_pred)

In [78]:
confusion_mat

array([[217,   5,  97,  45,  71,  26,  61],
       [  6,  27,   4,   0,  10,   4,   1],
       [ 45,   2, 245,  34,  87,  60,  52],
       [ 17,   0,  30, 711,  31,  30,  48],
       [ 65,   6, 126,  49, 254,  18,  95],
       [  8,   0,  34,  18,   5, 326,   8],
       [ 40,   1,  58,  62,  93,  37, 320]])